services:
  - type: web
    name: fragments-ai
    env: python
    plan: free
    region: frankfurt
    runtime: python
    buildCommand: |
      echo "🧠 Preparing to build the ultimate AI..."
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn main:app
    autoDeploy: true
    repo: https://github.com/mazsvensson248-jpg/Fragments-ai
    branch: main
    rootDir: .
    envVars:
      - key: PORT
        value: 10000
    healthCheckPath: /
    buildFilter:
      paths:
        - main.py
        - requirements.txt
        - static/
        - render.yaml
        - templates/
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
