services:
  - type: web
    name: fragments-ai-backend
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:8000 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    plan: free
    autoDeploy: true
    buildFilter:
      paths:
        - app.py
        - requirements.txt
        - render.yaml
        - templates/index.html
        - static/dummy.mp4
